version: "3"

services:


  schedulerservice:
    build: schedulerservice
    depends_on:
      - database
    ports:
      - 80:8080
    links:
      - database
      - peerservice
    environment:
      DATABASE_URL: database:3306
      DATABASE_USER: root
      DATABASE_PASSWORD: root
      DATABASE_DATABASE: schedulerDB
      PEER_AUTH: "5243980712315079823517089"
    restart: always

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    links:
      - database

  database:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: schedulerDB
      MYSQL_ROOT_PASSWORD: root